# TODO exemple item condense

language: "fr"

display:
  list: true

condense:
  iron_nugget: true
  gold_nugget: true
  raw_iron: true
  copper_ingot: true
  iron_ingot: true
  gold_ingot: true
  netherite_ingot: true
  diamond: true
  emerald: true
  redstone: true
  lapis_lazuli: true
  slime: true
  snow: true
  bone_meal: true
  melon_slice: true
  wheat: true

message:
  condense:
    resume: "§a[number] items condensé dans votre inventaire"
    item: "§a[item1] condensé en [item2]"
  error:
    inventory_full: "§4Inventaire plein: impossible de condenser [item1] en [item2]"
    ratio_zero: "§4Attention le ratio de conversion de [item1] est égal à 0"
